/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Angie
 */
public class StudentViewCRUD extends javax.swing.JFrame {
    
    private DefaultTableModel tableModel;
   
    public StudentViewCRUD() {
        initComponents();
        String[] columnNames = {"ID", "Names", "Last Names", "Document", "Average Grade"};
        tableModel = new DefaultTableModel(columnNames, 0);
        studentsTable.setModel(tableModel);
        
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = studentsTable.getSelectedRow();
                
                if (selectedRow != -1) {                   
                    int id = (int) studentsTable.getValueAt(selectedRow, 0);
                    
                    // Almacenar el ID del estudiante seleccionado
                    setSelectedStudentId(id);
                    
                    setTxtFieldId(String.valueOf(id));
                    
                    // Obtener los valores de la fila seleccionada
                    String names = (String) studentsTable.getValueAt(selectedRow, 1);
                    String lastnames = (String) studentsTable.getValueAt(selectedRow, 2);
                    String document = (String) studentsTable.getValueAt(selectedRow, 3);
                    String avgGrade = studentsTable.getValueAt(selectedRow, 4).toString();

                    // Asignar los valores a los campos de texto
                    setTxtFieldNames(names);
                    setTxtFieldLastnames(lastnames);
                    setTxtFieldDocument(document);
                    setTxtFieldAvgGrade(avgGrade);
                    
                }
            }
        });
        
        txtFieldId.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        txtFieldId = new javax.swing.JTextField();
        btnInsertStudent = new javax.swing.JButton();
        txtFieldAvgGrade = new javax.swing.JTextField();
        txtFieldNames = new javax.swing.JTextField();
        txtFieldLastnames = new javax.swing.JTextField();
        txtFieldDocument = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Course = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUpdateStudent = new javax.swing.JButton();
        btnDeleteStudent = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(studentsTable);

        btnInsertStudent.setText("Insert");

        jLabel1.setText("Id:");

        jLabel2.setText("Names:");

        jLabel3.setText("Lastnames:");

        Course.setText("Document:");

        jLabel5.setText("Average grade:");

        btnUpdateStudent.setText("Update");

        btnDeleteStudent.setText("Delete");

        btnClearForm.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(Course)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFieldAvgGrade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldDocument, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldLastnames, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldNames, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldNames, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldLastnames, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Course)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldAvgGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Course;
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnInsertStudent;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentsTable;
    private javax.swing.JTextField txtFieldAvgGrade;
    private javax.swing.JTextField txtFieldDocument;
    private javax.swing.JTextField txtFieldId;
    private javax.swing.JTextField txtFieldLastnames;
    private javax.swing.JTextField txtFieldNames;
    // End of variables declaration//GEN-END:variables
    
    public void setTxtFieldId(String txtFieldId){
        this.txtFieldId.setText(txtFieldId);
    }
    
    public String getTxtFieldNames(){
        return txtFieldNames.getText();
    }
    
    public void setTxtFieldNames(String txtFieldNames){
        this.txtFieldNames.setText(txtFieldNames);
    }
    
    public String getTxtFieldLastnames(){
        return txtFieldLastnames.getText();
    }
    
    public void setTxtFieldLastnames(String txtFieldLastnames){
        this.txtFieldLastnames.setText(txtFieldLastnames);
    }
    
    public String getTxtFieldDocument(){
        return txtFieldDocument.getText();
    }
    
    public void setTxtFieldDocument(String txtFieldDocument){
        this.txtFieldDocument.setText(txtFieldDocument);
    }
    
    public String getTxtFieldAvgGrade(){
        return txtFieldAvgGrade.getText();
    }
    
    public void setTxtFieldAvgGrade(String txtFieldAverageGrade){
        this.txtFieldAvgGrade.setText(txtFieldAverageGrade);
    }
    
    public JButton getBtnInsertStudent() {
        return btnInsertStudent;
    }
    
    public JButton getBtnUpdateStudent() {
        return btnUpdateStudent;
    }
    
    public JButton getBtnDeleteStudent() {
        return btnDeleteStudent;
    }
    
    public JButton getBtnClearForm() {
        return btnClearForm;
    }
    
    public void updateTable(Object[][] data) {
        tableModel.setRowCount(0); // Limpiar la tabla

        for (Object[] row : data) {
            tableModel.addRow(row);
        }
    }
    
    private int selectedStudentId;

    public int getSelectedStudentId() {
        return selectedStudentId;
    }

    public void setSelectedStudentId(int selectedStudentId) {
        this.selectedStudentId = selectedStudentId;
    }
    
}
